name: Deploy to Server

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  APP_NAME: react-admin-vite-bff

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ''
    outputs:
      IMAGE_TAG: ${{ steps.set-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: set-tag
        run: |
          TAG=$(date +%Y%m%d%H%M)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/admin/react-admin-vite-bff

            # 生成服务端 环境变量文件
            IMAGE_TAG="${{ needs.build.outputs.IMAGE_TAG }}"
            IMAGE_NAME="${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}"
            echo "IMAGE_TAG=$IMAGE_TAG" > .env.override
            echo "IMAGE_NAME=$IMAGE_NAME" >> .env.override

            docker-compose down || true
            docker-compose --env-file .env --env-file .env.override pull
            docker-compose --env-file .env --env-file .env.override up -d
